
server:
  port: 8089
spring:
  profiles: dev
  datasource:
    #url: jdbc:postgresql://postgres.cq71odd9ysze.us-east-2.rds.amazonaws.com:5432/postgres
    #username: postgres
    #password: postgres
    url: jdbc:postgresql://192.168.100.108:5432/exam
    username: desricardo
    password: ASUS2018
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect


logging:
  level:
    root: DEBUG
